import CoreGraphics
import Foundation

// These overloads preserve exact pre-existing API symbols. Defaulted parameters
// are part of Swift's exported constructor signature, so inserting a new one
// into an old initializer — `style` for dither, `showsTooltipOnHover` for cursor
// hover — replaces that symbol rather than extending it. Each frozen signature
// therefore lives on here as its own overload.
extension LivelineChartInteraction {
    /// The pre-hover initializer, preserved verbatim so existing call sites keep
    /// resolving to the same exported symbol. Hover-on-cursor stays off here.
    public init(
        scrub: Bool = true,
        windowStyle: LivelineWindowStyle = .default,
        lineMode: Bool = false,
        seriesToggleCompact: Bool = false,
        seriesLegendSide: LivelineLegendSide = .trailing,
        showsModeControls: Bool = false,
        showsSeriesControls: Bool = true
    ) {
        self.init(
            scrub: scrub,
            showsTooltipOnHover: false,
            windowStyle: windowStyle,
            lineMode: lineMode,
            seriesToggleCompact: seriesToggleCompact,
            seriesLegendSide: seriesLegendSide,
            showsModeControls: showsModeControls,
            showsSeriesControls: showsSeriesControls
        )
    }
}

extension LivelineChartConfiguration {
    public init(
        theme: LivelineThemeMode = .dark,
        window: TimeInterval = 30,
        windows: [LivelineWindowOption] = [],
        grid: Bool = true,
        badge: Bool = true,
        badgeVariant: LivelineBadgeVariant = .default,
        badgeTail: Bool = true,
        fill: Bool = true,
        pulse: Bool = true,
        lineWidth: CGFloat = 2,
        momentum: LivelineMomentum? = nil,
        autoDetectMomentum: Bool = true,
        scrub: Bool = true,
        exaggerate: Bool = false,
        showValue: Bool = false,
        valueMomentumColor: Bool = false,
        degen: LivelineDegenOptions? = nil,
        loading: Bool = false,
        paused: Bool = false,
        emptyText: String = LivelineLocalizedDefaults.emptyText,
        windowStyle: LivelineWindowStyle = .default,
        tooltipY: CGFloat = 14,
        tooltipOutline: Bool = true,
        orderbook: LivelineOrderbookData? = nil,
        referenceLine: LivelineReferenceLine? = nil,
        formatValue: @escaping (Double) -> String = LivelineFormatters.value,
        formatTime: @escaping (TimeInterval) -> String = LivelineFormatters.time,
        lerpSpeed: Double = 0.08,
        randomSeed: UInt32? = nil,
        snapshotElapsedTime: TimeInterval? = nil,
        padding: LivelinePadding = LivelinePadding(),
        lineMode: Bool = false,
        seriesToggleCompact: Bool = false,
        onHover: ((LivelineHoverPoint?) -> Void)? = nil,
        onWindowChange: ((TimeInterval) -> Void)? = nil,
        onModeChange: ((LivelineChartMode) -> Void)? = nil,
        onSeriesToggle: ((String, Bool) -> Void)? = nil
    ) {
        self.init(
            theme: theme,
            style: .standard,
            window: window,
            windows: windows,
            grid: grid,
            badge: badge,
            badgeVariant: badgeVariant,
            badgeTail: badgeTail,
            fill: fill,
            pulse: pulse,
            lineWidth: lineWidth,
            momentum: momentum,
            autoDetectMomentum: autoDetectMomentum,
            scrub: scrub,
            exaggerate: exaggerate,
            showValue: showValue,
            valueMomentumColor: valueMomentumColor,
            degen: degen,
            loading: loading,
            paused: paused,
            emptyText: emptyText,
            windowStyle: windowStyle,
            tooltipY: tooltipY,
            tooltipOutline: tooltipOutline,
            orderbook: orderbook,
            referenceLine: referenceLine,
            formatValue: formatValue,
            formatTime: formatTime,
            lerpSpeed: lerpSpeed,
            randomSeed: randomSeed,
            snapshotElapsedTime: snapshotElapsedTime,
            padding: padding,
            lineMode: lineMode,
            seriesToggleCompact: seriesToggleCompact,
            onHover: onHover,
            onWindowChange: onWindowChange,
            onModeChange: onModeChange,
            onSeriesToggle: onSeriesToggle
        )
    }

    public init(
        theme: LivelineThemeMode = .dark,
        window: TimeInterval = 30,
        windows: [LivelineWindowOption] = [],
        grid: Bool = true,
        badge: Bool = true,
        badgeVariant: LivelineBadgeVariant = .default,
        badgeTail: Bool = true,
        fill: Bool = true,
        pulse: Bool = true,
        endpointDecorations: Bool = true,
        fadeEffects: Bool = false,
        lineWidth: CGFloat = 2,
        momentum: LivelineMomentum? = nil,
        autoDetectMomentum: Bool = true,
        scrub: Bool = true,
        exaggerate: Bool = false,
        showValue: Bool = false,
        valueMomentumColor: Bool = false,
        degen: LivelineDegenOptions? = nil,
        loading: Bool = false,
        paused: Bool = false,
        emptyText: String = LivelineLocalizedDefaults.emptyText,
        windowStyle: LivelineWindowStyle = .default,
        tooltipY: CGFloat = 14,
        tooltipOutline: Bool = true,
        orderbook: LivelineOrderbookData? = nil,
        referenceLine: LivelineReferenceLine? = nil,
        activePoint: LivelineActivePoint? = nil,
        formatValue: @escaping (Double) -> String = LivelineFormatters.value,
        formatTime: @escaping (TimeInterval) -> String = LivelineFormatters.time,
        lerpSpeed: Double = 0.08,
        randomSeed: UInt32? = nil,
        snapshotElapsedTime: TimeInterval? = nil,
        padding: LivelinePadding = LivelinePadding(),
        lineMode: Bool = false,
        seriesToggleCompact: Bool = false,
        seriesLegendSide: LivelineLegendSide = .trailing,
        onHover: ((LivelineHoverPoint?) -> Void)? = nil,
        onWindowChange: ((TimeInterval) -> Void)? = nil,
        onModeChange: ((LivelineChartMode) -> Void)? = nil,
        onSeriesToggle: ((String, Bool) -> Void)? = nil
    ) {
        self.init(
            theme: theme,
            style: .standard,
            window: window,
            windows: windows,
            grid: grid,
            badge: badge,
            badgeVariant: badgeVariant,
            badgeTail: badgeTail,
            fill: fill,
            pulse: pulse,
            endpointDecorations: endpointDecorations,
            fadeEffects: fadeEffects,
            lineWidth: lineWidth,
            momentum: momentum,
            autoDetectMomentum: autoDetectMomentum,
            scrub: scrub,
            exaggerate: exaggerate,
            showValue: showValue,
            valueMomentumColor: valueMomentumColor,
            degen: degen,
            loading: loading,
            paused: paused,
            emptyText: emptyText,
            windowStyle: windowStyle,
            tooltipY: tooltipY,
            tooltipOutline: tooltipOutline,
            orderbook: orderbook,
            referenceLine: referenceLine,
            activePoint: activePoint,
            formatValue: formatValue,
            formatTime: formatTime,
            lerpSpeed: lerpSpeed,
            randomSeed: randomSeed,
            snapshotElapsedTime: snapshotElapsedTime,
            padding: padding,
            lineMode: lineMode,
            seriesToggleCompact: seriesToggleCompact,
            seriesLegendSide: seriesLegendSide,
            onHover: onHover,
            onWindowChange: onWindowChange,
            onModeChange: onModeChange,
            onSeriesToggle: onSeriesToggle
        )
    }
}
