import CoreGraphics
import Foundation

// These overloads preserve the exact pre-dither API symbols. Defaulted
// parameters are part of Swift's exported constructor signature, so inserting
// `style` into the old initializers would otherwise be source-breaking.
extension LivelineChartConfiguration {
    public init(
        theme: LivelineThemeMode = .dark,
        window: TimeInterval = 30,
        windows: [LivelineWindowOption] = [],
        grid: Bool = true,
        badge: Bool = true,
        badgeVariant: LivelineBadgeVariant = .default,
        badgeTail: Bool = true,
        fill: Bool = true,
        pulse: Bool = true,
        lineWidth: CGFloat = 2,
        momentum: LivelineMomentum? = nil,
        autoDetectMomentum: Bool = true,
        scrub: Bool = true,
        exaggerate: Bool = false,
        showValue: Bool = false,
        valueMomentumColor: Bool = false,
        degen: LivelineDegenOptions? = nil,
        loading: Bool = false,
        paused: Bool = false,
        emptyText: String = "No data to display",
        windowStyle: LivelineWindowStyle = .default,
        tooltipY: CGFloat = 14,
        tooltipOutline: Bool = true,
        orderbook: LivelineOrderbookData? = nil,
        referenceLine: LivelineReferenceLine? = nil,
        formatValue: @escaping (Double) -> String = LivelineFormatters.value,
        formatTime: @escaping (TimeInterval) -> String = LivelineFormatters.time,
        lerpSpeed: Double = 0.08,
        randomSeed: UInt32? = nil,
        snapshotElapsedTime: TimeInterval? = nil,
        padding: LivelinePadding = LivelinePadding(),
        lineMode: Bool = false,
        seriesToggleCompact: Bool = false,
        onHover: ((LivelineHoverPoint?) -> Void)? = nil,
        onWindowChange: ((TimeInterval) -> Void)? = nil,
        onModeChange: ((LivelineChartMode) -> Void)? = nil,
        onSeriesToggle: ((String, Bool) -> Void)? = nil
    ) {
        self.init(
            theme: theme,
            style: .standard,
            window: window,
            windows: windows,
            grid: grid,
            badge: badge,
            badgeVariant: badgeVariant,
            badgeTail: badgeTail,
            fill: fill,
            pulse: pulse,
            lineWidth: lineWidth,
            momentum: momentum,
            autoDetectMomentum: autoDetectMomentum,
            scrub: scrub,
            exaggerate: exaggerate,
            showValue: showValue,
            valueMomentumColor: valueMomentumColor,
            degen: degen,
            loading: loading,
            paused: paused,
            emptyText: emptyText,
            windowStyle: windowStyle,
            tooltipY: tooltipY,
            tooltipOutline: tooltipOutline,
            orderbook: orderbook,
            referenceLine: referenceLine,
            formatValue: formatValue,
            formatTime: formatTime,
            lerpSpeed: lerpSpeed,
            randomSeed: randomSeed,
            snapshotElapsedTime: snapshotElapsedTime,
            padding: padding,
            lineMode: lineMode,
            seriesToggleCompact: seriesToggleCompact,
            onHover: onHover,
            onWindowChange: onWindowChange,
            onModeChange: onModeChange,
            onSeriesToggle: onSeriesToggle
        )
    }

    public init(
        theme: LivelineThemeMode = .dark,
        window: TimeInterval = 30,
        windows: [LivelineWindowOption] = [],
        grid: Bool = true,
        badge: Bool = true,
        badgeVariant: LivelineBadgeVariant = .default,
        badgeTail: Bool = true,
        fill: Bool = true,
        pulse: Bool = true,
        endpointDecorations: Bool = true,
        fadeEffects: Bool = false,
        lineWidth: CGFloat = 2,
        momentum: LivelineMomentum? = nil,
        autoDetectMomentum: Bool = true,
        scrub: Bool = true,
        exaggerate: Bool = false,
        showValue: Bool = false,
        valueMomentumColor: Bool = false,
        degen: LivelineDegenOptions? = nil,
        loading: Bool = false,
        paused: Bool = false,
        emptyText: String = "No data to display",
        windowStyle: LivelineWindowStyle = .default,
        tooltipY: CGFloat = 14,
        tooltipOutline: Bool = true,
        orderbook: LivelineOrderbookData? = nil,
        referenceLine: LivelineReferenceLine? = nil,
        activePoint: LivelineActivePoint? = nil,
        formatValue: @escaping (Double) -> String = LivelineFormatters.value,
        formatTime: @escaping (TimeInterval) -> String = LivelineFormatters.time,
        lerpSpeed: Double = 0.08,
        randomSeed: UInt32? = nil,
        snapshotElapsedTime: TimeInterval? = nil,
        padding: LivelinePadding = LivelinePadding(),
        lineMode: Bool = false,
        seriesToggleCompact: Bool = false,
        seriesLegendSide: LivelineLegendSide = .trailing,
        onHover: ((LivelineHoverPoint?) -> Void)? = nil,
        onWindowChange: ((TimeInterval) -> Void)? = nil,
        onModeChange: ((LivelineChartMode) -> Void)? = nil,
        onSeriesToggle: ((String, Bool) -> Void)? = nil
    ) {
        self.init(
            theme: theme,
            style: .standard,
            window: window,
            windows: windows,
            grid: grid,
            badge: badge,
            badgeVariant: badgeVariant,
            badgeTail: badgeTail,
            fill: fill,
            pulse: pulse,
            endpointDecorations: endpointDecorations,
            fadeEffects: fadeEffects,
            lineWidth: lineWidth,
            momentum: momentum,
            autoDetectMomentum: autoDetectMomentum,
            scrub: scrub,
            exaggerate: exaggerate,
            showValue: showValue,
            valueMomentumColor: valueMomentumColor,
            degen: degen,
            loading: loading,
            paused: paused,
            emptyText: emptyText,
            windowStyle: windowStyle,
            tooltipY: tooltipY,
            tooltipOutline: tooltipOutline,
            orderbook: orderbook,
            referenceLine: referenceLine,
            activePoint: activePoint,
            formatValue: formatValue,
            formatTime: formatTime,
            lerpSpeed: lerpSpeed,
            randomSeed: randomSeed,
            snapshotElapsedTime: snapshotElapsedTime,
            padding: padding,
            lineMode: lineMode,
            seriesToggleCompact: seriesToggleCompact,
            seriesLegendSide: seriesLegendSide,
            onHover: onHover,
            onWindowChange: onWindowChange,
            onModeChange: onModeChange,
            onSeriesToggle: onSeriesToggle
        )
    }
}
