#!/usr/bin/env python3
"""Read and validate the Storybook scenario manifest."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SCENARIO_DOC = ROOT / "Docs" / "ScenarioMatrix.md"
SCENARIO_SOURCE_DIR = ROOT / "Examples" / "LivelineDemo" / "Sources"
GENERATED_SWIFT = SCENARIO_SOURCE_DIR / "StorybookScenarioIDs.generated.swift"
DEFAULT_MANIFEST = (
    ROOT
    / "Examples"
    / "LivelineDemo"
    / "Resources"
    / "storybook-scenarios.json"
)
ID_PATTERN = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


def load_manifest(path: Path) -> list[dict[str, str]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list) or not data:
        raise ValueError("manifest must be a non-empty JSON array")

    scenarios: list[dict[str, str]] = []
    seen: set[str] = set()
    for index, entry in enumerate(data):
        if not isinstance(entry, dict):
            raise ValueError(f"entry {index} must be an object")
        scenario = {
            "id": str(entry.get("id", "")).strip(),
            "area": str(entry.get("area", "")).strip(),
            "coverage": str(entry.get("coverage", "")).strip(),
        }
        if not ID_PATTERN.fullmatch(scenario["id"]):
            raise ValueError(f"entry {index} has an invalid id: {scenario['id']!r}")
        if scenario["id"] in seen:
            raise ValueError(f"duplicate scenario id: {scenario['id']}")
        if not scenario["area"] or not scenario["coverage"]:
            raise ValueError(f"entry {index} must include area and coverage")
        seen.add(scenario["id"])
        scenarios.append(scenario)
    return scenarios


def markdown_table(scenarios: list[dict[str, str]]) -> str:
    lines = ["| ID | Area | Coverage |", "| --- | --- | --- |"]
    for scenario in scenarios:
        lines.append(
            f"| `{scenario['id']}` | {scenario['area']} | "
            f"{scenario['coverage']} |"
        )
    return "\n".join(lines)


def swift_case_name(identifier: str) -> str:
    head, *tail = identifier.split("-")
    name = head + "".join(part[:1].upper() + part[1:] for part in tail)
    return name if not name[0].isdigit() else f"scenario{name}"


def swift_enum(scenarios: list[dict[str, str]]) -> str:
    cases = [(swift_case_name(scenario["id"]), scenario["id"]) for scenario in scenarios]
    names = [name for name, _ in cases]
    if len(set(names)) != len(names):
        raise ValueError("scenario ids collide after conversion to Swift case names")

    lines = [
        "// Generated by scripts/storybook_manifest.py from storybook-scenarios.json.",
        "// Do not edit this file by hand.",
        "",
        "enum StorybookScenarioID: String, CaseIterable {",
    ]
    lines.extend(f'    case {name} = "{identifier}"' for name, identifier in cases)
    lines.append("}")
    return "\n".join(lines)


def validate_derived_files(scenarios: list[dict[str, str]]) -> None:
    begin = "<!-- BEGIN GENERATED SCENARIO TABLE -->"
    end = "<!-- END GENERATED SCENARIO TABLE -->"
    document = SCENARIO_DOC.read_text(encoding="utf-8")
    if begin not in document or end not in document:
        raise ValueError("ScenarioMatrix.md is missing generated-table markers")
    actual = document.split(begin, 1)[1].split(end, 1)[0].strip()
    if actual != markdown_table(scenarios):
        raise ValueError(
            "ScenarioMatrix.md is stale; replace the generated table with "
            "`python3 scripts/storybook_manifest.py markdown`"
        )

    expected_swift = swift_enum(scenarios)
    if not GENERATED_SWIFT.exists() or GENERATED_SWIFT.read_text(encoding="utf-8").strip() != expected_swift:
        raise ValueError(
            "StorybookScenarioIDs.generated.swift is stale; replace it with "
            "`python3 scripts/storybook_manifest.py swift`"
        )

    scenario_sources = list(SCENARIO_SOURCE_DIR.glob("Storybook*Scenarios.swift"))
    source_text = "\n".join(path.read_text(encoding="utf-8") for path in scenario_sources)
    definition_count = source_text.count("= chart(")
    if definition_count != len(scenarios):
        raise ValueError(
            f"manifest has {len(scenarios)} entries but Swift has "
            f"{definition_count} scenario definitions"
        )

    used_cases = re.findall(
        r"^\s*id:\s*\.([A-Za-z_][A-Za-z0-9_]*),\s*$",
        source_text,
        flags=re.MULTILINE,
    )
    expected_cases = [swift_case_name(scenario["id"]) for scenario in scenarios]
    if len(used_cases) != len(expected_cases) or sorted(used_cases) != sorted(expected_cases):
        raise ValueError(
            "each generated Storybook scenario ID must be used exactly once by a Swift definition"
        )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("ids", "markdown", "swift", "validate"))
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    args = parser.parse_args()

    scenarios = load_manifest(args.manifest)
    if args.command == "ids":
        for scenario in scenarios:
            print(scenario["id"])
    elif args.command == "markdown":
        print(markdown_table(scenarios))
    elif args.command == "swift":
        print(swift_enum(scenarios))
    else:
        validate_derived_files(scenarios)
        print(f"Validated {len(scenarios)} Storybook scenarios")


if __name__ == "__main__":
    main()
